baseURL = "https://yelling.cloud/"
DefaultContentLanguage = "en"
title = "The Yelling Cloud"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
googleAnalytics = "G-4Q6YZVG9E7"

[Params]
  homeTitle = "The Yelling Cloud" # Set a different text for the header on the home page
  subtitle = "made by Rick Rackow"
  mainSections = ["post","posts"]
  logo = "imgs/yelling_cloud_logo.png" # Expecting square dimensions
  favicon = "imgs/yelling_cloud_logo.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true


[params.author]
  name = "Rick Rackow"
  email = "info@yelling.cloud"
  github = "RiRa12621"
  gitlab = "RiRa12621"
  twitter = "RiRa12621"
  linkedin = "rira12621"
  stackoverflow = "users/6336357/rick-rackow"
  #youtube = "user/username" # or channel/channelname

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1
